### ISSUE TITLE
Throwing Error : java.net.UnknownHostException: postgres

### ISSUE THREAD

**Issue by Yogesh102** [gravitonian/alfresco-dbp-keycloak-integration#1]
I cloned this project and did docker-compose up and it did not start properly  and throws below error.

 org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:345)
identity-service_1  |   at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:352)
identity-service_1  |   at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:287)
identity-service_1  |   at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1327)
identity-service_1  |   at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:499)
identity-service_1  |   at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:632)
identity-service_1  |   at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:604)
identity-service_1  |   at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:624)
identity-service_1  |   at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:430)
identity-service_1  |   at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:789)
identity-service_1  |   at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:138)
identity-service_1  |   at org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:64)
identity-service_1  |   at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:367)
identity-service_1  |   at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:65)
identity-service_1  |   at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$0(LiquibaseDBLockProvider.java:97)
identity-service_1  |   at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:544)
identity-service_1  |   at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:95)
identity-service_1  |   at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:144)
identity-service_1  |   at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:227)
identity-service_1  |   at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:137)
identity-service_1  |   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
identity-service_1  |   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
identity-service_1  |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
identity-service_1  |   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
identity-service_1  |   at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
identity-service_1  |   at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2298)
identity-service_1  |   at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:340)
identity-service_1  |   at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:253)
identity-service_1  |   at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:120)
identity-service_1  |   at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
identity-service_1  |   at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
identity-service_1  |   at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
identity-service_1  |   at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
identity-service_1  |   at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250)
identity-service_1  |   at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133)
identity-service_1  |   at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:565)
identity-service_1  |   at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536)
identity-service_1  |   at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
identity-service_1  |   at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
identity-service_1  |   at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
identity-service_1  |   at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
identity-service_1  |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
identity-service_1  |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
identity-service_1  |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
identity-service_1  |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
identity-service_1  |   at java.lang.Thread.run(Thread.java:748)
identity-service_1  |   at org.jboss.threads.JBossThread.run(JBossThread.java:320)
identity-service_1  | Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
identity-service_1  |   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:275)
identity-service_1  |   at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
identity-service_1  |   at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
identity-service_1  |   at org.postgresql.Driver.makeConnection(Driver.java:450)
identity-service_1  |   at org.postgresql.Driver.connect(Driver.java:252)
identity-service_1  |   at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:321)
identity-service_1  |   ... 52 more
identity-service_1  | Caused by: java.net.UnknownHostException: postgres
identity-service_1  |   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
identity-service_1  |   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
identity-service_1  |   at java.net.Socket.connect(Socket.java:589)
identity-service_1  |   at org.postgresql.core.PGStream.<init>(PGStream.java:68)
identity-service_1  |   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
identity-service_1  |   ... 57 more
identity-service_1  |
identity-service_1  | 19:06:49,451 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested via an OS signal
identity-service_1  | 19:06:49,554 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 48) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:84)
identity-service_1  |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
identity-service_1  |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
identity-service_1  |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
identity-service_1  |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
identity-service_1  |   at java.lang.Thread.run(Thread.java:748)
identity-service_1  |   at org.jboss.threads.JBossThread.run(JBossThread.java:320)
identity-service_1  | Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
identity-service_1  |   at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:162)
identity-service_1  |   at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2298)
identity-service_1  |   at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:340)
identity-service_1  |   at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:253)
identity-service_1  |   at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:120)
identity-service_1  |   at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
identity-service_1  |   at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
identity-service_1  |   at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
identity-service_1  |   at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
identity-service_1  |   at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250)
identity-service_1  |   at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133)
identity-service_1  |   at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:565)
identity-service_1  |   at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536)
identity-service_1  |   at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
identity-service_1  |   at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
identity-service_1  |   at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
identity-service_1  |   at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
identity-service_1  |   at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
identity-service_1  |   ... 6 more
identity-service_1  | Caused by: java.lang.RuntimeException: Failed to connect to database
identity-service_1  |   at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:373)
identity-service_1  |   at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:65)
identity-service_1  |   at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$0(LiquibaseDBLockProvider.java:97)
identity-service_1  |   at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:544)
identity-service_1  |   at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:95)
identity-service_1  |   at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:144)
identity-service_1  |   at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:227)
identity-service_1  |   at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:137)
identity-service_1  |   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
identity-service_1  |   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
identity-service_1  |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
identity-service_1  |   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
identity-service_1  |   at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
identity-service_1  |   ... 28 more
identity-service_1  | Caused by: java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/KeycloakDS
identity-service_1  |   at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:146)
identity-service_1  |   at org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:64)
identity-service_1  |   at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:367)
identity-service_1  |   ... 40 more
identity-service_1  | Caused by: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/KeycloakDS
identity-service_1  |   at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:690)
identity-service_1  |   at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:430)
identity-service_1  |   at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnec

**Comment by haveamission** [comment]
I am seeing a similar error - how did you solve it?
